import { useState, type FormEvent } from "react";
import { useAsync } from "@/hooks/useAsync";
import { Card } from "@/components/ui/Card"; import { Button } from "@/components/ui/Button";
import { ErrorBox, LoadingSpinner, PageHeader } from "@/components/PageBits"; import { Webhook } from "lucide-react";
interface Hook { id: string; url: string; events: string[] }
async function load(): Promise<Hook[]> { const r = await fetch("/webhooks"); if (!r.ok) throw new Error(`Unable to load webhooks (${r.status})`); const b = await r.json() as Hook[] | { webhooks: Hook[] }; return Array.isArray(b) ? b : b.webhooks; }
export function WebhooksPage() { const { data, loading, error, reload } = useAsync(load, []); const [url, setUrl] = useState(""); const [events, setEvents] = useState(""); const [actionError, setActionError] = useState<string | null>(null);
 async function request(path: string, body?: object) { setActionError(null); try { const r = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); if (!r.ok) throw new Error(`Request failed (${r.status})`); reload(); } catch (e) { setActionError(e instanceof Error ? e.message : String(e)); } }
 function create(e: FormEvent) { e.preventDefault(); void request("/webhooks", { url, events: events.split(",").map(x => x.trim()).filter(Boolean) }); }
 return <div className="p-4 max-w-4xl mx-auto space-y-3"><PageHeader title="Webhooks" icon={Webhook} />{loading && !data && <LoadingSpinner />}{(error || actionError) && <ErrorBox message={error ?? actionError ?? "Unknown error"} />}<Card><form onSubmit={create} className="flex flex-wrap gap-2"><input required type="url" className="input flex-1" placeholder="https://example.com/hook" value={url} onChange={e => setUrl(e.target.value)} /><input required className="input flex-1" placeholder="Events, comma separated" value={events} onChange={e => setEvents(e.target.value)} /><Button variant="primary">Create</Button></form></Card>{data?.map(h => <Card key={h.id}><div className="flex justify-between gap-2"><div><p className="font-mono text-sm">{h.url}</p><p className="text-xs text-fg-muted">{h.events.join(", ")}</p></div><Button size="sm" onClick={() => void request(`/webhooks/${encodeURIComponent(h.id)}/test`)}>Test</Button></div></Card>)}</div>; }
