/**
 * x402 micropayments + wallet (Frontier §20).
 *
 * x402 = the "HTTP 402 Payment Required" status code repurposed for
 * crypto/agent micropayments: a service returns 402 with a payment challenge
 * (amount, currency, payee, nonce), the client signs + pays via its wallet,
 * then retries the request with a payment proof header. The service verifies
 * the proof and returns 200 + the resource.
 *
 * This module ships:
 *   - Wallet: an in-memory balance + ECDSA key pair for signing payment
 *     authorizations. Real asymmetric cryptography (secp256k1) via Node's
 *     built-in `node:crypto` — no native dependencies.
 *   - X402Client: fetch with automatic 402-payment handling (1 retry after
 *     pay). Retries include the ECDSA signature + payer public key in x402
 *     headers so the server can verify the proof with public-key crypto.
 *   - paidFetch tool: exposes the pattern to the agent (WorkspaceWrite — the
 *     agent is paying, so it's a write-side action).
 *
 * Source: Frontier §20 "x402 micropayments + wallet"; the HTTP 402 pattern
 * used by cloudflare + others for paid APIs.
 *
 * ───────────────────────────────────────────────────────────────────────────
 *  CRYPTOGRAPHY
 * ───────────────────────────────────────────────────────────────────────────
 * `Wallet` holds an ECDSA **secp256k1** key pair generated by
 * `crypto.generateKeyPairSync`, or derived deterministically from a
 * `masterSecret` (backward-compat with the old HMAC API). All primitives come
 * from `node:crypto` (no extra dep).
 *
 *      // default: fresh random secp256k1 key pair
 *      keypair = generateKeyPairSync("ec", { namedCurve: "secp256k1" })
 *
 *      // backward-compat: masterSecret (old HMAC API) → deterministic key
 *      scalar   = HKDF-SHA256(ikm=address, salt=masterSecret,
 *                             info="x402v1:ecdsa-secp256k1", length=32)
 *      privKey  = ECPrivateKey(SEC1 DER, scalar, secp256k1 OID)
 *      pubKey   = createPublicKey(privKey)        // derived point
 *
 *      signature = ECDSA-SHA256(privKey, `${payee}|${currency}|${amount}|${nonce}`)
 *      verify    = createVerify("SHA256").verify(pubKey, signature)
 *
 * Properties:
 *   • Public-key verifiable: anyone with the payer's public key
 *     (`wallet.getPublicKey()`) can verify a receipt's signature — no shared
 *     secret required. This is the upgrade over the prior HMAC stub.
 *   • Different wallets produce DIFFERENT public keys + signatures.
 *   • `masterSecret` derivation is deterministic: the same `(masterSecret,
 *     address)` always yields the same key pair (stable public key). This
 *     preserves backward-compat for callers that pin a `masterSecret`.
 *   • `rotateKey()` generates a fresh random key pair; the public key
 *     changes, so receipts signed under the prior key no longer verify.
 *
 * NOTE on determinism: OpenSSL's default ECDSA signing uses a fresh random
 * nonce `k` per signature (RFC 6979 deterministic ECDSA is NOT enabled by
 * default in Node/OpenSSL). Therefore two `pay()` calls for the same
 * challenge produce DIFFERENT (but both valid) signatures. The wallet is
 * stable per key pair: repeated signatures verify under the same public key.
 *
 * What this is NOT:
 *   • Not on-chain — the wallet signs payment *authorizations*, not
 *     blockchain transactions. Settlement is out of scope (Tier 4).
 *   • Not persistent — keys live in memory only. On restart the wallet is
 *     "fresh" unless an explicit `privateKey`/`masterSecret` is supplied.
 *   • `address` is a public label bound into HKDF IKM (masterSecret path),
 *     not itself a cryptographic public key. Use `getPublicKey()` for that.
 * ───────────────────────────────────────────────────────────────────────────
 */
import type { ComponentHealth, ToolExecutor } from "@my-agent/core";
import { err, isRecord, ok, type ToolImpl } from "@my-agent/tools";
import type { ToolResult } from "@my-agent/core";
import {
  createHash,
  createPrivateKey,
  createPublicKey,
  createSign,
  createVerify,
  generateKeyPairSync,
  hkdfSync,
  randomBytes,
  KeyObject,
} from "node:crypto";
import { nowWallclock } from "@my-agent/core";

/** ECDSA curve used for all x402 signatures. */
export const ECDSA_CURVE = "secp256k1";
/** Signature envelope prefix (versioned + algorithm-tagged). */
export const SIG_PREFIX = "x402v1:ecdsa-secp256k1";

/** A payment challenge from a 402 response. */
export interface X402Challenge {
  amount: number; // smallest unit (e.g. satoshis / micro-USDC)
  currency: "USDC" | "SAT" | "FLOCK" | string;
  payee: string; // address / endpoint
  nonce: string;
  /** Human-readable resource description (for the agent's audit log). */
  memo?: string;
}

/** A signed payment authorization. */
export interface X402Receipt {
  challenge: X402Challenge;
  /** ECDSA-secp256k1 signature envelope: `x402v1:ecdsa-secp256k1:<der-hex>`. */
  signature: string;
  /** Wallet address that paid. */
  payer: string;
  /**
   * Payer's public key (SPKI DER hex) so a verifier can validate the
   * signature without an out-of-band key exchange. Optional for backward
   * shape-compat; always populated by `Wallet.pay()`.
   */
  publicKey?: string;
  /** Epoch ms when signed. */
  signedAt: number;
}

/** Balance per currency (smallest unit). */
export type Balance = Record<string, number>;

/**
 * Rich key lifecycle status for the `Wallet`.
 *
 * `address` is the public label bound into HKDF IKM (masterSecret path).
 * `masterSecretFingerprint` is a short SHA-256 fingerprint of the key *seed*
 * (the `masterSecret` when supplied, otherwise the private-key material) —
 * never the secret itself. `signingKeyFingerprint` fingerprints the public
 * key (SPKI DER). See {@link Wallet.keyStatus}.
 */
export interface KeyStatus {
  address: string;
  /** Signing algorithm. */
  algorithm: string;
  /** Short fingerprint of the key seed (masterSecret or private-key material). */
  masterSecretFingerprint: string;
  /** Short fingerprint of the public key (SPKI DER). */
  signingKeyFingerprint: string;
  /** 1-based: 0 until first rotateKey() call. */
  rotationCount: number;
  /** Epoch ms at construction. */
  createdAt: number;
  /** Epoch ms - createdAt. */
  ageMs: number;
}

/** HKDF domain-separator for the ECDSA private-key scalar (versioned). */
const HKDF_INFO_ECDSA = Buffer.from("x402v1:ecdsa-secp256k1", "utf8");
const MASTER_SECRET_BYTES = 32;
const ECDSA_SCALAR_BYTES = 32;
const FINGERPRINT_LEN = 12;

// ─── key helpers ─────────────────────────────────────────────────────────────

/** Canonical message signed over a challenge (do not include the address). */
function challengeToPayload(c: X402Challenge): string {
  // Address is intentionally NOT in the payload — it is the HKDF IKM for
  // masterSecret derivation, not part of the signed message. This avoids
  // address-key coupling forgery if two wallets share an address.
  return `${c.payee}|${c.currency}|${c.amount}|${c.nonce}`;
}

/** Short fingerprint of a secret for audit logs (never the secret itself). */
function fingerprint(b: Buffer): string {
  return createHash("sha256").update(b).digest("hex").slice(0, FINGERPRINT_LEN);
}

/**
 * Build a SEC1 ECPrivateKey DER blob for secp256k1 from a raw 32-byte scalar.
 *
 * ECPrivateKey ::= SEQUENCE {
 *   version INTEGER (1),
 *   privateKey OCTET STRING (32 bytes),
 *   parameters [0] EXPLICIT OBJECT IDENTIFIER -- secp256k1 (1.3.132.0.10)
 * }
 *
 * Deterministic for a fixed scalar — required so the masterSecret path yields
 * a stable key pair.
 */
function ecPrivateKeyDerFromScalar(scalar: Buffer): Buffer {
  if (scalar.length !== ECDSA_SCALAR_BYTES) {
    throw new Error(`x402: ECDSA scalar must be ${ECDSA_SCALAR_BYTES} bytes (got ${scalar.length})`);
  }
  // version: INTEGER 1
  const version = Buffer.from([0x02, 0x01, 0x01]);
  // privateKey OCTET STRING (length tag 0x20 = 32, since 32 < 128)
  const octet = Buffer.concat([Buffer.from([0x04, ECDSA_SCALAR_BYTES]), scalar]);
  // [0] EXPLICIT OID secp256k1 = 1.3.132.0.10 → 06 05 2B 81 04 00 0A
  const oid = Buffer.from([0x06, 0x05, 0x2b, 0x81, 0x04, 0x00, 0x0a]);
  const params = Buffer.concat([Buffer.from([0xa0, oid.length]), oid]);
  const inner = Buffer.concat([version, octet, params]);
  return Buffer.concat([Buffer.from([0x30, inner.length]), inner]);
}

/**
 * Derive a deterministic secp256k1 ECDSA key pair from `(masterSecret,
 * address)` via HKDF-SHA256 (RFC 5869). The same inputs always yield the
 * same key pair (stable public key). The HKDF output is a 32-byte scalar
 * packed into a SEC1 ECPrivateKey DER and loaded by `createPrivateKey`.
 */
function deriveEcdsaKeyPair(
  masterSecret: Buffer,
  address: string,
): { privateKey: KeyObject; publicKey: KeyObject } {
  const ikm = Buffer.from(address, "utf8");
  const scalarBuf = hkdfSync("sha256", ikm, masterSecret, HKDF_INFO_ECDSA, ECDSA_SCALAR_BYTES);
  const scalar = Buffer.from(scalarBuf);
  const der = ecPrivateKeyDerFromScalar(scalar);
  const privateKey = createPrivateKey({ key: der, format: "der", type: "sec1" });
  const publicKey = createPublicKey(privateKey);
  return { privateKey, publicKey };
}

/** Accepted `privateKey` option shapes: a KeyObject, PEM string, or SEC1 DER hex. */
type PrivateKeyInput = KeyObject | string | Buffer;

/** Normalize a `privateKey` option into a `KeyObject`. */
function loadPrivateKey(input: PrivateKeyInput): KeyObject {
  if (input instanceof KeyObject) return input;
  if (typeof input === "string") {
    if (input.includes("-----BEGIN")) {
      return createPrivateKey({ key: input, format: "pem" });
    }
    return createPrivateKey({ key: Buffer.from(input, "hex"), format: "der", type: "sec1" });
  }
  if (Buffer.isBuffer(input)) {
    return createPrivateKey({ key: input, format: "der", type: "sec1" });
  }
  throw new Error("x402: unsupported privateKey option (expected KeyObject | PEM | DER hex)");
}

/** Load a public key from a PEM string or SPKI DER hex string. */
function loadPublicKey(encoded: string): KeyObject {
  if (encoded.includes("-----BEGIN")) {
    return createPublicKey({ key: encoded, format: "pem" });
  }
  return createPublicKey({ key: Buffer.from(encoded, "hex"), format: "der", type: "spki" });
}

// ─── Wallet ──────────────────────────────────────────────────────────────────

/** A wallet holds a balance, an ECDSA key pair, and signs payment
 * authorizations. Fail-closed: throws on insufficient balance, invalid
 * amounts, or uninitialized key state. */
export class Wallet {
  private readonly balances: Balance;
  /** Payer address (public label; not itself a cryptographic pubkey). */
  readonly address: string;
  /** ECDSA private key (secp256k1). NEVER logged or persisted. */
  private privateKey: KeyObject;
  /** ECDSA public key (secp256k1). Safe to share for signature verification. */
  private publicKey: KeyObject;
  /** Original masterSecret if derived (backward-compat path); else undefined. */
  private masterSecret: Buffer | undefined;
  /** # of rotateKey() calls since construction. */
  private rotationCount = 0;
  /** Wallclock at construction (for key-status reporting). */
  private readonly createdAt: number;
  /** Audit log of all payments. */
  readonly receipts: X402Receipt[] = [];

  constructor(
    opts: { address?: string; initial?: Balance; masterSecret?: Buffer; privateKey?: PrivateKeyInput } = {},
  ) {
    this.address = opts.address ?? "my-agent-wallet";
    this.balances = { ...(opts.initial ?? {}) };
    this.createdAt = nowWallclock();
    if (opts.privateKey !== undefined) {
      this.privateKey = loadPrivateKey(opts.privateKey);
      this.publicKey = createPublicKey(this.privateKey);
      this.masterSecret = undefined;
    } else if (opts.masterSecret !== undefined) {
      this.masterSecret = opts.masterSecret;
      const kp = deriveEcdsaKeyPair(this.masterSecret, this.address);
      this.privateKey = kp.privateKey;
      this.publicKey = kp.publicKey;
    } else {
      const kp = generateKeyPairSync("ec", { namedCurve: ECDSA_CURVE });
      this.privateKey = kp.privateKey;
      this.publicKey = kp.publicKey;
      this.masterSecret = undefined;
    }
  }

  /** Get the current balance for a currency. */
  balance(currency: string): number {
    return this.balances[currency] ?? 0;
  }

  /** Read-only snapshot of all non-zero balances (currency → amount). */
  get balancesSnapshot(): Balance {
    return { ...this.balances };
  }

  /** Top up the wallet (deposit / faucet). */
  deposit(currency: string, amount: number): void {
    this.balances[currency] = this.balance(currency) + amount;
  }

  /**
   * Export the wallet's public key (SPKI DER by default) so others can
   * verify signatures without a shared secret.
   */
  getPublicKey(encoding: "hex" | "pem" = "hex"): string {
    if (encoding === "pem") {
      return this.publicKey.export({ type: "spki", format: "pem" }).toString();
    }
    return this.publicKey.export({ type: "spki", format: "der" }).toString("hex");
  }

  /**
   * Rotate the wallet's signing key: generate a fresh random secp256k1 key
   * pair. The public key changes, so receipts signed under the prior key no
   * longer verify under the new key.
   *
   * Returns the new 1-based rotation index (1 = first rotation).
   */
  rotateKey(): number {
    const kp = generateKeyPairSync("ec", { namedCurve: ECDSA_CURVE });
    this.privateKey = kp.privateKey;
    this.publicKey = kp.publicKey;
    // A rotated key is no longer masterSecret-derived.
    this.masterSecret = undefined;
    this.rotationCount += 1;
    return this.rotationCount;
  }

  /**
   * Sign a challenge (pay). Deducts the amount, appends a receipt, returns it.
   * Throws if the balance is insufficient or the amount is non-positive/non-finite.
   */
  pay(challenge: X402Challenge): X402Receipt {
    // R44: reject non-positive / non-finite amounts (a negative amount would
    // increase the balance; NaN makes it NaN permanently).
    if (!(challenge.amount > 0) || !Number.isFinite(challenge.amount)) {
      throw new Error(`x402: invalid payment amount ${challenge.amount} ${challenge.currency} (must be positive + finite)`);
    }
    const cur = this.balance(challenge.currency);
    if (cur < challenge.amount) {
      throw new Error(`x402: insufficient balance — have ${cur} ${challenge.currency}, need ${challenge.amount}`);
    }
    this.balances[challenge.currency] = cur - challenge.amount;
    const receipt: X402Receipt = {
      challenge,
      signature: signDeterministic(this.privateKey, challenge),
      payer: this.address,
      publicKey: this.getPublicKey(),
      signedAt: nowWallclock(),
    };
    this.receipts.push(receipt);
    return receipt;
  }

  /**
   * Verify an ECDSA signature over `challenge` using THIS wallet's public key.
   * Returns true iff the signature was produced by this wallet's current
   * private key over exactly this challenge.
   */
  verifySignature(challenge: X402Challenge, signature: string): boolean {
    return verifyEcdsaSignature(this.getPublicKey(), challenge, signature);
  }

  /**
   * Health tri-state. Returns `"Healthy"` while the key pair is initialized.
   *
   * For key lifecycle detail (rotation count, age, fingerprints), see
   * {@link Wallet.keyStatus}. Rich detail is published separately via the
   * `health` runtime event (`detail` field) — the tri-state stays stable so
   * the laneboard aggregates cleanly.
   */
  health(): ComponentHealth {
    return "Healthy";
  }

  /**
   * Rich key lifecycle snapshot. SAFE to log / emit — fingerprints are short
   * SHA-256 hex prefixes of the raw bytes, not the bytes themselves.
   *
   * Use this to surface key status to observability (e.g. wire into the
   * `health` runtime event as `detail`).
   */
  keyStatus(): KeyStatus {
    // Seed material for the fingerprint: masterSecret if derived, else the
    // private-key (SEC1 DER) bytes.
    const seed = this.masterSecret ?? this.privateKey.export({ type: "sec1", format: "der" });
    const pubDer = this.publicKey.export({ type: "spki", format: "der" });
    return {
      address: this.address,
      algorithm: ECDSA_CURVE,
      masterSecretFingerprint: fingerprint(Buffer.isBuffer(seed) ? seed : Buffer.from(seed)),
      signingKeyFingerprint: fingerprint(pubDer instanceof Buffer ? pubDer : Buffer.from(pubDer)),
      rotationCount: this.rotationCount,
      createdAt: this.createdAt,
      ageMs: nowWallclock() - this.createdAt,
    };
  }
}

// ─── ECDSA sign / verify ─────────────────────────────────────────────────────

/**
 * ECDSA-SHA256 (secp256k1) signature over the challenge using the wallet's
 * private key. Returns the envelope `x402v1:ecdsa-secp256k1:<der-hex>`.
 *
 * Uses `crypto.createSign("SHA256")` per the public-key signing contract.
 * Note: OpenSSL's default ECDSA uses a random nonce, so the output is NOT
 * byte-deterministic — but every signature verifies under the public key.
 */
function signDeterministic(privateKey: KeyObject, c: X402Challenge): string {
  const payload = challengeToPayload(c);
  const sig = createSign("SHA256").update(payload).sign(privateKey);
  return `${SIG_PREFIX}:${sig.toString("hex")}`;
}

/** Parse a signature envelope into its raw DER bytes, or `null` if malformed. */
function parseSignature(signature: string): Buffer | null {
  if (typeof signature !== "string") return null;
  // SIG_PREFIX = "x402v1:ecdsa-secp256k1" (contains a colon); the envelope is
  // `${SIG_PREFIX}:<hex>`.
  const head = `${SIG_PREFIX}:`;
  if (!signature.startsWith(head)) return null;
  const hex = signature.slice(head.length);
  if (hex.length === 0 || hex.length % 2 !== 0 || !/^[0-9a-fA-F]+$/.test(hex)) return null;
  return Buffer.from(hex, "hex");
}

/**
 * Verify an ECDSA-secp256k1 signature over `challenge` using a public key
 * (PEM string or SPKI DER hex). Standalone — usable to verify ANY payer's
 * signature given their public key, with no shared secret.
 *
 * Returns `false` (never throws) for malformed signatures or unsupported
 * keys, so callers can treat it as a pure boolean predicate.
 */
export function verifyEcdsaSignature(
  publicKey: string,
  challenge: X402Challenge,
  signature: string,
): boolean {
  const sigBytes = parseSignature(signature);
  if (!sigBytes) return false;
  let pub: KeyObject;
  try {
    pub = loadPublicKey(publicKey);
  } catch {
    return false;
  }
  try {
    return createVerify("SHA256").update(challengeToPayload(challenge)).verify(pub, sigBytes);
  } catch {
    return false;
  }
}

// ─── X402Client (fetch with 402-payment handling) ────────────────────────────

export interface X402FetchOptions {
  method?: "GET" | "POST";
  headers?: Record<string, string>;
  body?: string;
  /** Max payment attempts (default 2: initial 402 → 1 pay → retry). */
  maxPaymentAttempts?: number;
}

/** Response from a paid fetch. */
export interface X402FetchResult {
  ok: boolean;
  status: number;
  body?: string;
  /** Payments made (audit trail for the agent). */
  receipts: X402Receipt[];
  /** If the final response was a 402, the unresolved challenge. */
  pendingChallenge?: X402Challenge;
}

/**
 * Parse a 402 challenge from a response.
 * Expects a JSON body: `{ "x402": { amount, currency, payee, nonce, memo? } }`.
 */
function parse402(body: string, status: number): X402Challenge | null {
  if (status !== 402) return null;
  try {
    const obj = JSON.parse(body) as { x402?: X402Challenge };
    const c = obj.x402;
    if (!c || typeof c.amount !== "number" || typeof c.payee !== "string") return null;
    return c;
  } catch {
    return null;
  }
}

/**
 * X402Client — wraps `fetch` with automatic 402-payment handling.
 * On 402, the wallet pays + the request is retried with payment-proof headers
 * (`x402-proof`, `x402-signature`, `x402-pubkey`) so the server can verify
 * the ECDSA signature with public-key crypto.
 */
export class X402Client {
  constructor(private wallet: Wallet) {}

  async fetch(url: string, opts: X402FetchOptions = {}): Promise<X402FetchResult> {
    // R44: a fetch needs ≥2 attempts to complete a pay→retry cycle; clamp up.
    const maxAttempts = Math.max(2, opts.maxPaymentAttempts ?? 2);
    // R44: per-fetch timeout (default 30s) so a hung server can't stall the agent.
    const timeoutMs = 30_000;
    const receipts: X402Receipt[] = [];
    let pending: X402Challenge | undefined;
    let paid = false; // R44: pay AT MOST ONCE per fetch (a second 402 = proof rejected)

    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      const headers: Record<string, string> = { ...(opts.headers ?? {}) };
      // Attach the latest receipt as proof (if any), including the ECDSA
      // signature + payer public key for server-side public-key verification.
      if (receipts.length > 0) {
        const last = receipts[receipts.length - 1]!;
        headers["x402-proof"] = JSON.stringify(last);
        headers["x402-signature"] = last.signature;
        headers["x402-pubkey"] = this.wallet.getPublicKey();
      }
      let resp: Response;
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), timeoutMs);
      try {
        resp = await fetch(url, {
          method: opts.method ?? "GET",
          headers,
          body: opts.body,
          signal: controller.signal,
        });
      } catch (e) {
        clearTimeout(timer);
        const aborted = (e as Error).name === "AbortError";
        return {
          ok: false,
          status: 0,
          receipts,
          pendingChallenge: pending,
          body: aborted
            ? `x402: fetch timed out after ${timeoutMs}ms`
            : `x402: network error: ${(e as Error).message}`,
        };
      }
      clearTimeout(timer);
      if (resp.status === 402) {
        const body = await resp.text();
        const challenge = parse402(body, resp.status);
        if (!challenge) {
          return { ok: false, status: 402, body, receipts, pendingChallenge: undefined };
        }
        // R44: if we've ALREADY paid and the server returns 402 again, the proof
        // was rejected (or it's a new challenge). Don't pay a second time — that
        // would drain the wallet for a resource we never get. Return unresolved.
        if (paid) {
          return {
            ok: false,
            status: 402,
            body: "x402: proof rejected (server returned 402 after payment)",
            receipts,
            pendingChallenge: challenge,
          };
        }
        try {
          const receipt = this.wallet.pay(challenge);
          receipts.push(receipt);
          paid = true;
        } catch (e) {
          // Insufficient balance — stop.
          return {
            ok: false,
            status: 402,
            body: (e as Error).message,
            receipts,
            pendingChallenge: challenge,
          };
        }
        pending = challenge;
        continue; // retry with proof
      }
      // Success (2xx) or other status — return.
      const body = await resp.text();
      return {
        ok: resp.ok,
        status: resp.status,
        body,
        receipts,
        pendingChallenge: undefined,
      };
    }
    // Loop exhausted without 2xx — return the last 402 challenge.
    return { ok: false, status: 402, receipts, pendingChallenge: pending };
  }
}

// ─── paidFetch tool (exposes the pattern to the agent) ───────────────────────

export function makePaidFetchTool(
  wallet: Wallet,
  _toolExecutor?: ToolExecutor,
): ToolImpl {
  const client = new X402Client(wallet);
  return {
    meta: {
      name: "paid_fetch",
      args: {
        type: "object",
        properties: {
          url: { type: "string" },
          method: { type: "string", enum: ["GET", "POST"] },
        },
        required: ["url"],
      },
      requiredMode: "WorkspaceWrite", // paying = write side
    },
    async run(args): Promise<ToolResult> {
      if (!isRecord(args) || typeof args.url !== "string") return err("paid_fetch", "url required");
      const result = await client.fetch(args.url, { method: (args.method === "POST" ? "POST" : "GET") as "GET" | "POST" });
      return ok("paid_fetch", result);
    },
  };
}

export type { ComponentHealth, ToolExecutor };
